import 'modules/common/svg-icon';
import 'modules/layout/layout';
import 'modules/example/custom';
import 'modules/example/default';
import 'modules/example/lit';
import 'modules/timer/custom';
import 'modules/timer/lite';
import 'modules/timer/lit';
import './style.less';
